version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  app:
    container_name: student_list
    build:
      context: .
      dockerfile: .docker/server.dockerfile
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}
      - DEV_DIALECT=${DEV_DIALECT}

